language: php
php:
  - 7.4
sudo: true
env:
  global:
    - CC_TEST_REPORTER_ID=b1d819eafb45dd064e0cca0c20e616aee7833b0688ea5c21dc2e978a1768137a
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - |
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
    chmod +x ./cc-test-reporter;
    ./cc-test-reporter before-build;
script:
  - |
    set -e;
    composer update --prefer-stable --no-interaction --no-suggest;
    composer cs;
    composer test-coverage;
after_script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi;
